/*
 * This file was automatically generated by a script.
 * To regenerate this file, run: pnpm assets gen
 */

import DocumentLight from "./DocumentLight.png";
import FolderLight from "./FolderLight.png";

export { DocumentLight, FolderLight };
